### ISSUE TITLE
Version 1.71

### ISSUE THREAD

**Issue by SuNflOw1991** [adoxa/ansicon#105]
Hi everyone,

I wonder if there is also a compiled version of v1.71? 

At OneDrive I already have found v1.70 but if I use that version with IntellJIDEA (PhpStorm) the `$` sign is missing.  
V1.66 is completely not working. If I run a command in my terminal, it never will stop running. I have to close the terminal and have to open a new one.

My config says:
```bash
"C:\ansicon\x64\ansicon.exe" -p "C:\Program Files\Git\bin\sh.exe" -login -i
```

I'm running Windows 10 with 

> PhpStorm 2017.2 Build #PS-172.3317.83, built on July 18, 2017
> Licensed to *NAME_REMOVED*
> Subscription is active until April 17, 2018
> JRE: 1.8.0_152-release-915-b5 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

My `.minttyrc` file says:
```ini
BoldAsFont=-1
Font=Fira Code
FontHeight=12
BellFlash=yes
Term=xterm
```

And `.bashrc` says:
```bash
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

On Windows 7 v1.66 is still running without any issues.

**Comment by adoxa** [comment]
Don't know exactly what state I've left it in, but I've pushed v1.72 and uploaded the [x64 version](https://1drv.ms/u/s!Au0XnS-c3hgNgQD81HqQKK9AK4qy).

If you're using mintty, you shouldn't need ANSICON at all.

**Comment by SuNflOw1991** [comment]
Thanks a lot for your efforts. I'll will test it as soon I'm at home.

> If you're using mintty, you shouldn't need ANSICON at all.  

Sadly some colors are present and some not. For composer I need ANSICON to show colors. For git not. Maybe I missed something in my configuration process?

**Comment by adoxa** [comment]
Mintty is a terminal emulator, so it uses redirected output, which ANSICON will ignore. Hm, perhaps you only need the `ANSICON` (or `ANSICON_VER`) environment variable for composer to use color? ... Or explicitly add `--ansi` to the composer command (which is probably what the environment variable would effectively do).

Nice to know it works (_so far_, anyway).

**Comment by SuNflOw1991** [comment]
I've tested this again...

Without ANSICON:
![no-ansicon](https://user-images.githubusercontent.com/943484/29115748-fa358640-7cf8-11e7-8e82-c6752232ab1d.png)
![no-ansicon--ansi](https://user-images.githubusercontent.com/943484/29115753-fd2e1344-7cf8-11e7-9d40-5e882d9e7a0b.png)

With ANSICON:
![ansicon](https://user-images.githubusercontent.com/943484/29115765-0619feaa-7cf9-11e7-92e9-6c53a342c44d.png)
![ansicon--ansi](https://user-images.githubusercontent.com/943484/29115768-07f7bc62-7cf9-11e7-9cc3-3e10da9df40b.png)

This is from JetBrains PHPStorm.
If I run Mintty directly, I don't need ANSICON at all. This is really strange in my opinion.

**Comment by adoxa** [comment]
As Richard mentioned in #106, you shouldn't need ANSICON from PHP v7.2, either; he also mentioned in #91 that it worked directly, but maybe that was due to running from `cmd`.

It is strange that running `sh` directly supports ANSI, but not when running `sh --login -i` (at least, I suppose that's what's you mean).  If you're still going to use ANSICON, I would suggest removing `-p` - it's not needed when you run a program directly.
