### ISSUE TITLE
"TAB" key reset cursor position to beginning of current row

### ISSUE THREAD

**Issue by WURMiL** [adoxa/ansicon#109]
Hi,

On Windows 10 64bit the filename autocomplete feature by pressing "TAB" key moves cursor to the start of current row and overwrites original text.

regards,
WURMi ;)

**Comment by adoxa** [comment]
That's strange, it looks like the current position is not being read/set correctly. A workaround is to add a sequence to the end of the prompt: e.g. `set PROMPT=$P$G$E[m`.

**Comment by maryo** [comment]
This behaviour appears since 1.80

**Comment by adoxa** [comment]
Fixed with 1.82.
