### ISSUE TITLE
Windows Defender detected virus

### ISSUE THREAD

**Issue by aplocher** [adoxa/ansicon#112]
I realize this isn't the first issue to be submitted notifying you that ansicon is coming back as a virus.  It seems most of the detections were done by third party software, but it looks like Windows Defender is now detecting it, which means out of the box Windows is going to prevent anyone from ever using this, and is significantly worse (IMO) than a third party tool flagging it.

Has there been a submission to the Windows Defender team disputing the false positive?

It looks like they have resources to file a dispute at these two links:

https://www.microsoft.com/en-us/wdsi/antimalware-support/developer-resources
https://www.microsoft.com/en-us/wdsi/antimalware-support/file-submission-guide (search this page for the word "dispute")

**Comment by adoxa** [comment]
Might leave it till 1.82, which I hope to do in the next week or two.

**Comment by adoxa** [comment]
I have an older 10 (Version 1703 (OS Build 15063.786)) with current definitions (1.261.1049.0 11 Feb 2018) and that seemed to work fine with 1.82. I shall now probably skip 1709 and go straight to 1803 (assuming it lets me), so it might be a while before I test again.

**Comment by aplocher** [comment]
I just downloaded Ansicon 1.82 and 1.83 without any issues.  When I (re)downloaded 1.81 it very quickly called it a virus and deleted (or quarantined) it.  Strange... I guess it's ok now lol, should I close this?  Might not be a bad idea to submit the app to those file dispute URLs anyway, just to get it "on the radar" over at Microsoft.

**Comment by aplocher** [comment]
As is the case for me too, now.  This time both Chrome and Windows Defender complained right away.  

![image](https://user-images.githubusercontent.com/1132447/39653242-15a0c8ca-4fa5-11e8-9f3a-020700857461.png)

![image](https://user-images.githubusercontent.com/1132447/39653272-3727cc8c-4fa5-11e8-9133-3a92c9b94bb2.png)
