### ISSUE TITLE
ansicon as dll for loading in Reactos and MSWindowsNT systemwide.

### ISSUE THREAD

**Issue by blackcrack** [adoxa/ansicon#114]
Hi,
ansicon as dll for loading in Reactos systemwide.
if we have a dll-file where it is possible to load in WinNT (XP/Vista/Win7 and up) systems could it maybe possible to use in any winnt . With them it is maybe possible for support asccii sequences in batchfiles
and maybe able to use it as driver for the systemvariables as interpreter, maybe both, the old dos
variables and the linux variables( $e[..... and ESC[..... . And using/supporting both in batchfiles and in console/prompt.
An ansicon.dll file and ansicon64.dll file with registering in the NT system could be pretty cool !
This could download via bitsadmin and registering via regsvr32  (or if you use inno-setup just with switches) in a batch file and could have a better spreading/distributing and this should be under gpl2 like reactos ;)
In reactos could you be the developer for this.. (btw, reactos it is near on the 0.5 on daily builds and testable in virtualbox. The fully server2003 is not the end target it goes furter !)

if you have this as loadable and registering dll, could you use maybe inno-setup with switches for 
installing and registering via regsvr32 /q 

best regards
Blacky
blackysgate.de

https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by adoxa** [comment]
ReactOS is open source, so if they want their console to have escape sequences, they can do so directly.

Once we all eventually migrate to 10, ANSICON becomes redundant.

**Comment by blackcrack** [comment]
at moment mus i use Win7 and Openmandriva as Server in the basement :)
i want migration to Reactos if it's finish or usable so far and this can be for all the end solution ;)
i guess it's 0.8/0.9 so far to be in dry towels.
and Reactos it is at moment in direction of Win Server 2003 and therewith not directly programming in the whole "crap"\*s* not directly in cmd (is maby also not really well) it's maybe better if it is 
as "driver" who it is hang in on cmd and the dll-files be registered.
By the way, can i register the both dll-files via regsrv32 ? 
(time stupid questions because, i have read nothing of it)
and thank you for your fast reply \:))))

best regards
Blacky

**Comment by adoxa** [comment]
No, the DLLs cannot be registered.

ANSICON works by injecting a DLL (using `CreateRemoteThread` on the parent process, or modifying the import table of a newly created process) and redirecting the imports.

**Comment by blackcrack** [comment]
could you make it able to registered for nt to be able for put in the system and then as system dll be registered ? \*smiiile* 
(well i am not a programmer, this i leave to others ;) but it's well to know..
i have enough to do with batch, php and play around of different systems and programs;) )

**Comment by adoxa** [comment]
No, it won't work that way.

**Comment by blackcrack** [comment]
why ? (for my/and other understanding)
why  could it make not as dll ? (this tread could you take as Example later)
must this directly programming in [cmd.exe (reactos)](https://github.com/mirror/reactos/tree/master/reactos/base/shell/cmd) to be it works ? and then, why ?
Could you make maybe patches for this cmd.exe in reactos ? \*s*
therewith could you code hold alive into the future ...

best kindly regards
Blacky

**Comment by blackcrack** [comment]
check it out and test it ;) , the daily iso's be downloadable 
on the headpage reactos.org at the 3 buttons right sided if desktop view :)
you can programming also in if it's not supported natively 
and send a patch on github/reactos :+1: 

but so far ..
it's solved so far
