### ISSUE TITLE
Showing double directory location after update Windows 10 version 1803

### ISSUE THREAD

**Issue by walangkaji** [adoxa/ansicon#119]
hi,
today I've update my windows to version 1803,

but, my problem is after update that, i got my CMD have two directory,

normally: 
`C:\WINDOWS\system32>command here`
now: 
`C:\WINDOWS\system32>C:\WINDOWS\system32>command here`

when I uninstall with command `ansicon.exe -i`, they're going back to normal again.

I hope this problem can be fixed.
I use Latest release ANSICON v1.83

**Comment by adoxa** [comment]
Can you run `ansicon -l5`, then just `exit`? That will start a new `CMD` with logging and immediately exit it. Post `%temp%\ansicon.log` and we'll see if we can find where the double's coming from. Does `echo ^[[1+h` make any difference? (`^[` is `Ctrl+[`.)

**Comment by walangkaji** [comment]
@adoxa this is a log result:

```
ANSICON (64-bit) v1.83 log (5) started 2018-05-04 17:04:42

ansicon (7588): C:\WINDOWS\system32\cmd.exe (7016)
ansicon (7588):   64-bit console (base = 00007FF6_46F40000)

cmd (7016): hDllInstance = 00000000_AC000000
cmd (7016): WriteConsoleW: 40 "Microsoft Windows [Version 10.0.17134.1]"
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 52 "(c) 2018 Microsoft Corporation. All rights reserved."
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 29 "C:\Program Files\ansicon\x64>"
```
for echo:
```
C:\Program Files\ansicon\x64>C:\Program Files\ansicon\x64>echo ^[[1+h
[[1+h

C:\Program Files\ansicon\x64>C:\Program Files\ansicon\x64>
```
log:
```
ANSICON (64-bit) v1.83 log (5) started 2018-05-04 17:04:42

ansicon (7588): C:\WINDOWS\system32\cmd.exe (7016)
ansicon (7588):   64-bit console (base = 00007FF6_46F40000)

cmd (7016): hDllInstance = 00000000_AC000000
cmd (7016): WriteConsoleW: 40 "Microsoft Windows [Version 10.0.17134.1]"
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 52 "(c) 2018 Microsoft Corporation. All rights reserved."
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 29 "C:\Program Files\ansicon\x64>"
cmd (7016): WriteConsoleW: 7 "[[1+h\r\n"
cmd (7016): WriteConsoleW: 2 "\r\n"
cmd (7016): WriteConsoleW: 29 "C:\Program Files\ansicon\x64>"
```


[http://prntscr.com/jdlpfe](http://prntscr.com/jdlpfe)

**Comment by adoxa** [comment]
> cmd (7860): WriteConsoleW: 2 "\r\n"
> cmd (7860): WriteConsoleW: 29 "C:\Program Files\ansicon\x64>"
> cmd (7860): Terminating
That shows that it's only intercepted once, so it's apparently not `CMD` sending it twice. I'll have to think about where to add extra logging.

> cmd (9284): WriteConsoleW: 7 "[[1+h\r\n"
That shows that you typed a literal `^` and a literal `[`, when you should have pressed `Ctrl+[` to generate the escape character.

**Comment by walangkaji** [comment]
@adoxa oh im sorry,
this a log with echo and press Ctrl+[
log:
```
ANSICON (64-bit) v1.83 log (5) started 2018-05-04 21:49:03

ansicon (4376): cmd.exe (8240)

cmd (8240): hDllInstance = 00000000_AC000000
cmd (8240): WriteConsoleW: 2 "\r\n"
cmd (8240): WriteConsoleW: 7 "\e[1+h\r\n"
cmd (8240): WriteConsoleW: 2 "\r\n"
cmd (8240): WriteConsoleW: 4 "C:\>"
```

**Comment by adoxa** [comment]
Okay, since you didn't say that fixed it, I guess it didn't. I'll get back to you...

**Comment by walangkaji** [comment]
I've try in 3 computer and they're same got double directory path.

I don't know why.

**Comment by adoxa** [comment]
Is it only `CMD`'s prompt doubling up? How about a line ending with `^`, does `More?` double up? How about `set /p=Prompt?`, does `Prompt?` double up? How about `powershell`'s prompt?

**Comment by walangkaji** [comment]
@adoxa 
```
C:\Program Files\ansicon\x64>C:\Program Files\ansicon\x64>set /p=Prompt?
Prompt?Prompt?

C:\Program Files\ansicon\x64>C:\Program Files\ansicon\x64>
```
it's just only on CMD,
powershell & ubuntu bash just fine.

**Comment by adoxa** [comment]
I don't know when I'll be getting 1803, so would you be able to email me its `cmd.exe`?

**Comment by walangkaji** [comment]
of course, where i can send it?

**Comment by adoxa** [comment]
Thanks, hopefully I can track it down. My email is in the readme.

**Comment by ethaligan** [comment]
Hey,

The version 1.66 is working fine on 1803 but not the latest one (1.83).

**Comment by walangkaji** [comment]
@ethaligan hey, thanks for info. it's working fine after i try it.

so, do you've same problem with double directory when use v1.83?

**Comment by ethaligan** [comment]
yeah I had the same problem before turning to 1.66

**Comment by adoxa** [comment]
After asking for `cmd` I ended up downloading 1803 after all. I've got one more change to make, then I'll install 1803 and have a look-see.

**Comment by walangkaji** [comment]
thanks @adoxa 

still waiting for next update 👍

**Comment by adoxa** [comment]
I've made [url=http://adoxa.altervista.org/ansicon/ansi184-wip.zip]v1.84-wip[/url] (work-in-progress) available, which fixes this issue. I don't expect much to change for the release (just making sure it compiles with the MinGWs), so consider this stable and suitable for use.

It seems to be a bug with the console itself - I create a second buffer to assist with wrap detection and that's where the duplicate comes from. Fortunately, in this case it was easy to work around.

**Comment by walangkaji** [comment]
@adoxa yeah, finally worked.
solved 👍
