### ISSUE TITLE
vue-cli-service build fails to complete with ansicon

### ISSUE THREAD

**Issue by layanto** [adoxa/ansicon#127]
See https://github.com/vuejs/vue-cli/issues/3504#issuecomment-468213738

With ansicon, vue-cli-service fails to complete. No problem with Windows cmd.exe. Strangely once I run build once with Windows cmd.exe, after that no problem with running build in ansicon.

I noticed that when I run build with cmd.exe, it creates node_modules/.cache folder but ansicon doesn't.

Steps to reproduce:
1. Install nodejs
2. Install vue-cli-service by running "npm install -g @vue/click"
3. Create new Vue project by running "vue create test"
4. "cd test" to navigate into newly created project
5. "npm run build" and build never finishes. Running same command with cmd.exe completes successfully.

**Comment by adoxa** [comment]
Should be fixed with v1.88.
