### ISSUE TITLE
Underline not working on Windows 7 ?

### ISSUE THREAD

**Issue by BUZZARDGTA** [adoxa/ansicon#131]
### **_Underline_** not working on Windows 7 ? (And probably 8 & 8.1)

So here is a picture showing my problem :
https://imgur.com/a/HjHhQOl

On the left of the picture you can see 2 cmd's of my application :
- Windows 7 Virutal Machine (x86 buid 7601) (showing the problem (can't underline the text)).
- Windows 10 (x64 v2004) 

In ANSICON documentation it said that it should support underline so I was just wondering if's part of a bug or an error I made ?
Thanks for any help, thanks for creating this great ANSICON tool, and have a nice day...

Note : Both are using the same code wich is : `<esc>[4m` "String Exemple" `<esc>[24m`

P.S : Is there please a real way to code or call a command to detect if ANSICON is installed or not ?

**Comment by adoxa** [comment]
No, ANSICON does not support underline, it makes the background intense, instead. 10's native sequences support underline, but even then ANSICON still uses intense background.

Check for the presence of the `ANSICON_VER` environment variable (or perhaps `ANSICON`, but there are some situations where that could be defined even if ANSICON is not installed). Alternatively, a slightly more portable test is environment variable `CLICOLOR`.

**Comment by BUZZARDGTA** [comment]
Alright, so thanks for your really quick answer, I appreciate.

The problem is that now, before to launch my program, I need to detect if ANSICON is installed or not for old windows versions.

If I don't do that, Windows 10 will have this background instead of the underline.

So I thinked of doing that in the begginning of my batch application, i didn't really successed it and I'm still trying to code it at the moment cause it's not working yet.

> :: start of the debug code made to support old Windows versions.
set ANSICON=<esc>[90m
echo %ANSICON% | find /i "0" >nul&&(
    goto INSTALLANSICON
    ) || (
        goto CONTINUELAUNCHER
        )
:: End of the debug code made to support old Windows

PS : I've already tried what you suggested me but it didn't worked. . . Even if ANSICON was uninstalled with `ANSICON -u` it was always echoing the version of ANSICON.exe : "189" :/

**Comment by adoxa** [comment]
> > echo %ANSICON% | find /i "0" >nul&&(

That won't work, since it's no longer going to the console, so it won't be processed. [Here's](https://stackoverflow.com/a/38059894) a method that uses Powershell, but of course then you have to know if Powershell is supported (and Powershell is slow). A simple approach might be to use `ver | find " 10"`, although it's hardly robust. I've thought about adding underline to ANSICON, but I don't really want to change its behaviour. Finally, I could add an option to ANSICON to test if native sequences are supported and/or a conditional install.

> PS : I've already tried what you suggested me but it didn't worked. . . Even if ANSICON was uninstalled with `ANSICON -u` it was always echoing the version of ANSICON.exe : "189" :/

You want `-pu` to unhook; `-u` only removes the registry entry.

**Comment by BUZZARDGTA** [comment]
Thank you so much :D

With your help and all your answers, I will now be able to code a fix for the following problem : 
**Windows 10** using **ANSICON** **block** **underlines** and show **background** instead.

As soon as I will found the perfect code I will publish it here so it could help the people who are facing my problem too.

**Comment by BUZZARDGTA** [comment]
:: start of the debug code made to support old Windows versions.
@echo off
setlocal
:LAUNCHER
cls
for /f "tokens=2 delims=[]" %%i in ('ver') do set version=%%i
for /f "tokens=2-3 delims=. " %%i in ("%version%") do set version=%%i.%%j
if "%version%"=="10.0" (
    goto WINDOWS10
    ) || (
        goto WINDOWS
)
if "%version%"=="6.4" (
    goto WINDOWS10
    ) || (
        goto WINDOWS
)

:WINDOWS
:: ANSICON WILL BE INSTALLED IN WINDOWS 2000, Vista, 7, 8, 8.1
echo %ANSICON_VER% >"log.txt"
pause
find "189" log.txt >nul || if "%errorlevel%"=="0" (
    goto INSTALLANSICON
    ) ELSE (
        goto CONTINUELAUNCHER
)
pause

:WINDOWS10
:: ANSICON WILL NOT BE INSTALLED IN WINDOWS 10

:INSTALLANSICON
:: ANSICON INSTALLATION IS HERE ON THE END OF THE SCRIPT TO AVOID ANY ERRORS
if exist "%PROGRAMFILES(X86)%" (
    if not exist "x64\ansicon.exe" mshta.exe vbscript:Execute^("msgbox ""The program can't start because 'x64\ansicon.exe' is missing in the folder."" & Chr(10) & Chr(10) & ""Please download Illegal Services again."",0+16+0+0+4096+65536,""Illegal Services Checker"":close"^) > "%tmp%\msgbox.vbs" && del /f /q /s "%tmp%\msgbox.vbs" >nul && exit
    if not exist "x64\ANSI64.dll" mshta.exe vbscript:Execute^("msgbox ""The program can't start because 'x64\ANSI64.dll' is missing in the folder."" & Chr(10) & Chr(10) & ""Please download Illegal Services again."",0+16+0+0+4096+65536,""Illegal Services Checker"":close"^) > "%tmp%\msgbox.vbs" && del /f /q /s "%tmp%\msgbox.vbs" >nul && exit
    if not exist "x64\ANSI32.dll" mshta.exe vbscript:Execute^("msgbox ""The program can't start because 'x64\ANSI32.dll' is missing in the folder."" & Chr(10) & Chr(10) & ""Please download Illegal Services again."",0+16+0+0+4096+65536,""Illegal Services Checker"":close"^) > "%tmp%\msgbox.vbs" && del /f /q /s "%tmp%\msgbox.vbs" >nul && exit
    call "x64\ansicon.exe" -i >nul && goto LAUNCHER
    )

if not exist "%PROGRAMFILES(X86)%" (
    if not exist "x86\ansicon.exe" mshta.exe vbscript:Execute^("msgbox ""The program can't start because 'x86\ansicon.exe' is missing in the folder."" & Chr(10) & Chr(10) & ""Please download Illegal Services again."",0+16+0+0+4096+65536,""Illegal Services Checker"":close"^) > "%tmp%\msgbox.vbs" && del /f /q /s "%tmp%\msgbox.vbs" >nul && exit
    if not exist "x86\ANSI32.dll" mshta.exe vbscript:Execute^("msgbox ""The program can't start because 'x86\ANSI32.dll' is missing in the folder."" & Chr(10) & Chr(10) & ""Please download Illegal Services again."",0+16+0+0+4096+65536,""Illegal Services Checker"":close"^) > "%tmp%\msgbox.vbs" && del /f /q /s "%tmp%\msgbox.vbs" >nul && exit
    call "x86\ansicon.exe" -i >nul && goto LAUNCHER
)
:CONTINUELAUNCHER
pause
:: End of the debug code made to support old Windows versions.

**Comment by BUZZARDGTA** [comment]
So for the people wo still need to "Avoid ANSICON Windows 10 Installation" for they're batch applications, I made this for my application. You can use the code and modify it for yourself. . .
➖➖➖➖➖➖➖➖➖➖
https://pastebin.com/i1DTasj2
➖➖➖➖➖➖➖➖➖➖
Thanks again to @adoxa for he's work, help and simply to made ANSICON v1.89 <3

**Comment by adoxa** [comment]
>    echo %ANSICON_VER% >"log.txt"
>    pause
>    find "189" log.txt >nul || if "%errorlevel%"=="0" (

That's convoluted. It won't work with a different version and `||` only works when `%errorlevel% != 0` (that's the definition). `if defined ANSICON_VER goto CONTINUELAUNCHER` is all you need (and `goto WINDOWS10` should be `goto CONTINUELAUNCHER`). Bear in mind it won't work for anyone using the legacy console (the version is still 10, but sequences are not supported).

**Comment by BUZZARDGTA** [comment]
hmm thanks again for the clarification and help :)

Ho yeah and I copied the parts used inside of my app and pasted them grouped so that's why "goto WINDOWS10 should be goto CONTINUELAUNCHER" but yeah ofc you're right, I use :WINDOWS10 for other stuff too in my app.

Btw I have no clue of what is an "legacy console" but alright ^-^

**Comment by adoxa** [comment]
Properties > Options > Use legacy console. It's the same console as previous versions of Windows (some programs might need it).

**Comment by BUZZARDGTA** [comment]
@adoxa Hi, excuse me I'm so sorry to bother you for that simple question but I wanna know if there's a big difference to run your program x32 on a x64 or is it exactly the same result ?

Cause I wanna reduce the place in my app and remove all x64 applications cause I think x86 work anyways, do you think it is a good idea ? Thanks in advance and sorry for bother . . .

**Comment by adoxa** [comment]
If you only have 32-bit programs you only need the 32-bit version; if you have 64-bit programs, you will need the 64-bit version (DLLs do not intermix). If you're using a batch file (for `echo` or `type` to have sequences) you will probably be using a 64-bit `cmd.exe`.

**Comment by BUZZARDGTA** [comment]
Well I have both x64 and x32 but in the idea of reducing the space of my app I wanna remove all x64 bits since I think they are not usefull cause x32 work, I don't know if I should remove x64 bits or not...

**Comment by adoxa** [comment]
If you only want x32 and still want to hook `cmd` you could re-run the batch via ANSICON, something like:

```batch
if not defined ANSICON if %PROCESSOR_ARCHITECTURE%==AMD64 (
  ansicon %0 %*
  goto :eof
)
```

The user runs a 64-bit `cmd`, which runs the 32-bit ANSICON, which runs the 32-bit `cmd`. If you have no need to hook `cmd` then there's no real need to worry about x64.

**Comment by BUZZARDGTA** [comment]
Hmm thanks for your answers !
