### ISSUE TITLE
Doesn't Support ANSI Escape Codes

### ISSUE THREAD

**Issue by ghost** [adoxa/ansicon#133]
Windows 10 version 21H1

![Bad](https://i.ibb.co/Bqskbtk/a.png)

**Comment by adoxa** [comment]
That looks like it's outputting ` 33` and not `\33`, so I'd say your source is bad.

**Comment by ghost** [comment]
> That looks like it's outputting ` 33` and not `\33`, so I'd say your source is bad.

nvm problem solved lol woops https://github.com/microsoft/terminal/issues/10834
