### ISSUE TITLE
sequences.txt may have a wrong 

### ISSUE THREAD

**Issue by MeowDWing** [adoxa/ansicon#138]
when I do output by Python in Windows Terminal(cmd.exe), I find it:
In sequences.txt, the doc says:
[...m
                38;2;#	foreground based on index (0-255)
		38;5;#;#;# foreground based on RGB
But 38;2;#;#;# can output the right color based on RGB, or not 5,
such as: 
`python
print('\033[38;5;255;255;0m color \033[m')
`
the output is white because '0m'
but when I change the '5' to '2',
cmd will successfully output by yellow

**Comment by MeowDWing** [comment]
![QQ截图20230809185941](https://github.com/adoxa/ansicon/assets/67000868/1883b600-5d90-4f4d-9071-b2edd58da1fd)

**Comment by adoxa** [comment]
I actually fixed that three years ago (almost a year after releasing 1.89), but I was still working on it and never pushed; something must have happened to sidetrack me and I've still yet to get back to it...

**Comment by blackcrack** [comment]
hmmmmmmmmmmmm....   
\033[art of font (fad, blink or something);forground;background\033[0m  
  
or something.. more remind me no more.. bit 2 times of 255;255 cant it be, it's to mutch, only one 255  
and then must be the right colorcode ... so 3 color codes and not 4, so far i remind me ... ;)  
at moment coding i am in linux and have no mutch time to invest in something, but i have see your issue..  
  
Hey @adoxa , why do you not open the Disscussion ?  
for help exactly for something :smile:  
best greetings  
blacky
