### ISSUE TITLE
Boost::Test output is not processed, escape codes printed

### ISSUE THREAD

**Issue by Malvineous** [adoxa/ansicon#75]
If you run a program using the Boost::Test framework then the ANSI codes get printed to the screen instead of being processed by ANSICON.

Here is a test program:

    #include <iostream>
    #define BOOST_TEST_MODULE example
    #define BOOST_TEST_DYN_LINK
    #include <boost/test/unit_test.hpp>

    BOOST_AUTO_TEST_CASE(test)
    {
        BOOST_TEST_MESSAGE("\033[1;33mtest\033[34ming\033[0m");
    }

Compiled and run like so:

    cl /MD /EHsc test.cpp /I C:\local\boost_1_57_0 /link /libpath:C:\path\to\boost_1_57_0\lib32-msvc-12.0
    test --log_level=message

And the output looks like this:

    Running 1 test case...
    ←[1;33mtest←[34ming←[0m
    Test case test did not check any assertions
    
    *** No errors detected

Running `ansicon test.exe` does not work - the only way I could get it to work is by piping the output through ANSICON with `test.exe | ansicon` but then stderr is jumbled up within the coloured stdout output, making it unreadable.  Having to run `test.exe 2>&1 | ansicon` does work but then you lose the ability to distinguish between stderr and stdout.

Would it be possible to get this bug fixed so that running a Boost::Test program will correctly get its output intercepted and the ANSI codes processed, as with other programs?

In case you don't have Boost readily available, here is [a precompiled test.exe](http://www.shikadi.net/files/ansicon-test.zip) from the code above.

**Comment by Malvineous** [comment]
Whoops, I just solved this one while reading issue #71.  I'd copied the ANSICON files into `%windir%\system32` and as that thread explains, this folder gets redirected to `%windir%\syswow64` when running a 32-bit program, so ANSICON could not be found when running the 32-bit Boost::Test program.  (As a side note, I wonder why 64-bit programs use a folder with 32 in the name, and 32-bit programs use a folder with 64 in the name?)

Moving the ANSICON install to `%windir%` fixed the problem.  Maybe a note could be made somewhere warning people why installing into `system32` could cause problems!

Sorry for the noise.

**Comment by adoxa** [comment]
I shall indeed have to make a note about installing to `system32`.

Regarding stderr/stdout, I wrote [Errout](http://errout.adoxa.vze.com/) for that very reason.

(I believe `system32` was used to distinguish 32-bit programs from the 16-bit `system`. The 32 name was kept with the change to 64 bits. `wow64` is Windows on Windows64.)

**Comment by adoxa** [comment]
I shall indeed have to make a note about installing to `system32`.

Regarding stderr/stdout, I wrote [Errout](http://errout.adoxa.vze.com/) for that very reason.

(I believe `system32` was used to distinguish 32-bit programs from the 16-bit `system`. The 32 name was kept with the change to 64 bits. `wow64` is Windows on Windows64.)
