### ISSUE TITLE
Got incorrect output - codes of colors insted colored text for casperjs

### ISSUE THREAD

**Issue by RocketRaccoon** [adoxa/ansicon#76]
Using ansicon 1.66 x64 on win7. Got following output after installation:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
...
←[32;1mPASS←[0m 'Sign Up' form found
←[32;1mPASS←[0m 'Register as' select was found
←[32;1mPASS←[0m 'Username' input was found
←[32;1mPASS←[0m 'Email' input was found
←[32;1mPASS←[0m 'Password' input was found
←[32;1mPASS←[0m 'Sign up' button was found
←[32;1mPASS←[0m 'Username' validation was shown
←[37;41;1mFAIL←[0m 'Email' validation was shown
←[33m#    type: assertVisible←[0m
←[33m#    file: signup.js←[0m
←[33m#    subject: false←[0m
←[33m#    selector: "div > input[name=\"email\"]+ p"←[0m
```

What's wrong?

**Comment by RQuadling** [comment]
Can you type ``set ansicon`` and tell us the what you get?

**Comment by adoxa** [comment]
You've cut a bit too much - are you running this through Java, CScript, or what? In any event, try with [1.70](https://onedrive.live.com/redir?resid=D18DE9C2F9D17ED!127&authkey=!ADZkdErqDeWb2cg&ithint=file%2czip).

**Comment by RocketRaccoon** [comment]
I'm running `casperjs` according to following [recomendation](http://docs.casperjs.org/en/latest/installation.html#casperjs-on-windows).
I will try 1.7 version and `set ansicon` today lately and provide more information.

**Comment by adoxa** [comment]
I can confirm that `casperjs.exe` fails with 1.66, but works with 1.70. I wasn't able to test it with a script, though (using SlimerJS Lite).

**Comment by RocketRaccoon** [comment]
Confirm. 1.70 works fine with test scripts. Thanks!
![2015-03-29_1212](https://cloud.githubusercontent.com/assets/3246428/6884843/ec244d56-d60c-11e4-9c7c-ab964a7c2d77.png)

**Comment by adoxa** [comment]
Great. I better hurry up and release it...

**Comment by Gimmeaphatbeat** [comment]
+1
