### ISSUE TITLE
Set CLICOLORS environment variable

### ISSUE THREAD

**Issue by jhasse** [adoxa/ansicon#77]
Hi!

First of all thanks for ANSICON, I really love it! Makes outputting colored text cross-platform a lot easier.

When I was configuring a Jenkins continuous integration server on Windows I noticed how hard it is to tell all programs that it's okay to output ANSI color codes. There are some programs looking for `ANSICON` (which of course only works out-of-the-box on cmd.exe, not with Jenkins) and others look for the `TERM` variable. I think it would be great if there was a standard environment variable for all platforms.

I searched a bit and found that `CLICOLOR` comes close, but is currently only used on OSX AFAIK. That's why I created a page to document this: http://bixense.com/clicolors/

Would you be willing to set `CLICOLOR` additionally to `ANSICON`? If yes, that would be a great first step. I'm also planning to create issues for MSYS 2, Cygwin and various Linux distributions to set this variable.

Thanks in advance and I'm looking forward to your comments on this :)

edit: Miss-spelled `CLICOLOR` in the title, sorry!

**Comment by adoxa** [comment]
I shall add it as a dynamic variable (like `ANSICON_VER`):

    C:\>set cli
    Environment variable cli not defined

    C:\>echo %CLICOLOR%
    1

**Comment by jhasse** [comment]
Yes, that would be great :)

**Comment by adoxa** [comment]
Done.

**Comment by jhasse** [comment]
Thanks!
