### ISSUE TITLE
Very weird behaviour.

### ISSUE THREAD

**Issue by rquadling** [adoxa/ansicon#79]
Hi.

Sometimes I do daft things and ```type``` a binary file. Most of the time, this results in a screen full of garbage and a sad face as I realise I've ```type```-d and not used the correct viewer app.

But occasionally, not only do I get a screen full of garbage, the font seems to get rewritten! Which is rather funny. But completely useless.

As an example, here is a screen shot after having ```type```-d a CygWin DLL.

![messedup](https://cloud.githubusercontent.com/assets/12801/7473064/febf79c8-f32f-11e4-9bff-ae003d58c2bd.png)

To resolve this, I have to close the console and reopen it. No permanent damage seems to be done. If I pipe the command I just ran to a file, it is fine. Just something wonky going on when certain binary strings are processed by ANSICON.

Obviously, ```type```-ing binary files is a daft thing, but sometimes I forget.

**Comment by HelioGuilherme66** [comment]
Won't a simple clear screen solve it?

I tried to replicate, but after sending "cls" it came back to normal.

(I did try to reset the console with:
mode CON: CP SELECT=yyy

where yyy is the one reported by:
mode CON: CP /STATUS
)

Please note that I am not using colors in my prompt.

**Comment by rquadling** [comment]
```CLS``` doesn't do it and I'm not sure how the codepage was changed anyway. It is a super super edge case and more of a curiosity than anything else. Frankly, ```type```-ing a binary file ... is asking for trouble. But at least it is better than the bad old days of DOS. Doing that and every ^G character would issue what seemed like a 2s beeeeeeeep. Very annoying!

**Comment by adoxa** [comment]
^N (Ctrl+N, character 14, SO shift-out, LS1 Locking-shift One) switches to the DEC Special Graphics Character Set (see the readme); ^O (Ctrl+O, character 15, SI shift-in, LS0 Locking-shift Zero) restores the normal characters. This was added back in 1.40, when a user requested the line drawing characters.

**Comment by rquadling** [comment]
Aha! Thanks for the explanation.
