### ISSUE TITLE
Alignment issues with true type monospaced fonts.

### ISSUE THREAD

**Issue by rquadling** [adoxa/ansicon#81]
Hi.

When I'm outputting text with a background, the alignment is off.

This only seems to apply to TrueType monospaced fonts (Lucida Console and Consolas - that's all I've got).

ScreenCap : ![ansicon alignment issue](https://cloud.githubusercontent.com/assets/12801/8593350/dc350544-262e-11e5-9b24-dff58af23f84.png)

As a log file :
```
  [37;41m          [39;49m  
  [37;41m  Notice  [39;49m  The following requested order identifiers could not be located.
  [37;41m  Notice  [39;49m  The following requested order identifiers could not be located.
  [37;41m          [39;49m  
```
'' is the escape character.

**Comment by adoxa** [comment]
That's a problem with the console itself (an issue with ClearType, I think, since it doesn't happen with my patched conhost using TerminalVector bitmaps).

**Comment by adoxa** [comment]
Here's a patch to fix it, assuming you have the same version as me:

```
# Patch conhost (7 SP1 x64) to clip to the rectangle (prevents ClearType from
# drawing to the previous cell) and stop adding 1 to the right edge (it's
# already correct).
# Jason Hood, 13 July, 2015.

File: ..\sysnative\conhost.exe
00255A: 06			[ 02 ]
002567: 0F 1F 80 00		[ 01 8C 14 A4 ]
012924: 00			[ 01 ]
01293B: 06			[ 02 ]
03AE27: 0F 1F 84 00 00 00	[ 44 01 8C 2C C4 02 ]
03AE42: 06			[ 02 ]
03CDF9: 00			[ 01 ]
03CE15: 06			[ 02 ]
03D000: 00			[ 01 ]
03D015: 06			[ 02 ]
043C18: 01			[ 00 ]
```

That's a [bwpatch](http://misc.adoxa.vze.com/#bwpatch) file, but it's small enough you could just use a hex editor (new bytes on the left, replacing original bytes on the right). Here's how to apply it (in an Administrator command prompt, adjust name & paths as necessary):

```
C:\Windows\system32>takeown /f conhost.exe

SUCCESS: The file (or folder): "C:\Windows\system32\conhost.exe" now owned by user "Adoxa\Jason".

C:\Windows\system32>icacls conhost.exe /grant Jason:F
processed file: conhost.exe
Successfully processed 1 files; Failed processing 0 files

C:\Windows\system32>ren conhost.exe conhost~1.exe

C:\Windows\system32>copy conhost~1.exe conhost.exe
        1 file(s) copied.

C:\Windows\system32>bwpatch -f conhost.crk

```

Now all your new consoles should be right.

**Comment by rquadling** [comment]
I'm on Windows 7. Different file.

**Comment by adoxa** [comment]
Email it to me, please.

**Comment by rquadling** [comment]
Upgraded to Windows 10. No issue.
