### ISSUE TITLE
ansicon -i (and -I) segmentation fault when used with Git Bash for Windows

### ISSUE THREAD

**Issue by survivor0804** [adoxa/ansicon#82]
It would be desirable if ansicon would also work with Windows bash emulators like Git Bash for Windows. Please disregard this if you don't plan to support other Windows shells. This is the Git session when I try to install ansicon:

Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

Nino@LAPTOP ~
$ cd /c/Users/Nino/AppData/Roaming/Ansicon160/x64/

Nino@LAPTOP ~/AppData/Roaming/Ansicon160/x64
$ ansicon -i
Segmentation fault

Nino@LAPTOP ~/AppData/Roaming/Ansicon160/x64
$

**Comment by rquadling** [comment]
Does git bash not already support ANSI colours?

**Comment by adoxa** [comment]
@rquadling: Yes, but it only applies to MSYS-compiled programs (so probably everything in Git's bin directory, but nothing else).

@survivor0804: After having another look (it's come up a few times), `-p` (which is what you should be using, rather than `-i`, which really only installs for `cmd` and implies `-p`) does not crash for me (v1.66 & v1.70), but nor does it work (it looks like it hooks everything, but without effect); starting the shell via ansicon worked fine (change your shortcut). You may also be able to add `ansicon -p` to your startup group, thus hooking Explorer and anything it starts, but I guess there's also a chance it'll prevent you from running anything...

**Comment by survivor0804** [comment]
I just realized that there is a more serious problem with ansicon: git itself has stopped working. It appears that other processes started from cmd.exe are also affected. Please see this link: https://github.com/adoxa/ansicon/issues/61. Don’t know if the problem only applies to x64.

**Comment by adoxa** [comment]
Is that with 1.70? The `-i` option is what's affecting `cmd` (the issue shows how to fix that, but in short: Run `cmd /d`, then `ansicon -u`). If it is happening with 1.70, then at least as far as Git Bash is concerned, changing your shortcut to start with `x86\ansicon` should do it.

Turns out `ansicon -p` within Bash will just not work - Bash creates a subshell, so that is the parent and I'd need to hook the grandparent. I don't intend to do that at this stage.

**Comment by survivor0804** [comment]
No. This is with 1.60. When trying to build the 1.70 I get:

NMAKE : fatal error U1073: don't know how to make 'x64\ansicon.obj'

when using ansicon64 target; no x64 ansicon is built with default target. I’m using VS2013.

Yes. The issue shows how to avoid the “Git has stopped working...” situation but I need to use git in my build process and at the same time debug with pry which uses ansi codes. All this within cmd.exe. 

Git Bash does not throw segment fault with ansicon x86 but does not work either.

Rosendo

**Comment by adoxa** [comment]
Examine the output of `nmake /nologo /f makefile.vc /p` and you should find `{}.c{x64}.obj:` among the inference rules - if not, that's why it's not working (the macros section should have `BITS = 64` and `DIR = x64`). Here's what I get with 2010 Pro:

```
C:\Projects\ansicon>cl
Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Projects\ansicon>nmake /nologo /f makefile.vc V=1 x64\ansicon.obj
        cl /c /nologo /W3 /O2 /MD /D_CRT_SECURE_NO_WARNINGS /Fox64\ansicon.obj .\ansicon.c
ansicon.c
```

Going back to the original issue, here's what happens for me:

```
C:\Program Files (x86)\Git>ansicon --version
ANSICON (64-bit) version 1.66 (21 September, 2013).

C:\Program Files (x86)\Git>ruby --version
ruby 1.9.3p125 (2012-02-16) [i386-mingw32]

C:\Program Files (x86)\Git>bin\sh --login -i
Welcome to Git (version 1.8.3-preview20130601)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

admin@ADOXA /
$ ruby -e 'print "\e[Ctest\n"'
←[Ctest

admin@ADOXA /
$ ansicon -p

admin@ADOXA /
$ ruby -e 'print "\e[Ctest\n"'
←[Ctest

admin@ADOXA /
$ logout

C:\Program Files (x86)\Git>ansicon bin\sh --login -i
Welcome to Git (version 1.8.3-preview20130601)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

admin@ADOXA /
$ ruby -e 'print "\e[Ctest\n"'
 test
```

It seems Ruby 2 (`ruby 2.0.0p481 (2014-05-08) [x64-mingw32]`) supports escapes directly.

**Comment by survivor0804** [comment]
If I force BITS = 64 the inference rule exists but linker fails with: image exceeds maximum extent with base address AC000000 and size D000.

Yes, ruby 2 apparently supports escape code but pry (ruby debugger) doesn’t:

C:\>ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]

C:\>ruby -e 'print "\e[Ctest\n"'
test

C:\>pry
[0F[1] pry(main)> 5001

The ansicon command (1.60) to start bin\sh on Git’s directory gives dialog “sh.exe has stopped working”

**Comment by adoxa** [comment]
> If I force BITS = 64 the inference rule exists but linker fails with: image exceeds maximum extent with base address AC000000 and size D000. 

That sounds like you're not actually using the 64-bit compiler - examine the output of `cl` and note the target, it should be `for x64`; if it's `for 80x86`, then it's still 32-bit. Further comments should be directed to #80.

> Yes, ruby 2 apparently supports escape code but pry (ruby debugger) doesn’t: 

Ah, well. I tried `gem install pry` in my earlier 2, but it complained about SSL, so I tried `gem install --source=http://rubygems.org pry`, then it complained about a build environment, so I started MSYS with mingw-builds and that worked (although the documents still wanted https), and after all that, pry didn't use (or at least, output) escape sequences, anyway (nor did the successful install into 1.9.3). My quota is rather low, so I'd rather not update just atm. I guess `ansicon pry.bat` crashes, too?

> The ansicon command (1.60) [...]

Stop using 1.60 - try with [1.70](
https://onedrive.live.com/redir?resid=D18DE9C2F9D17ED!127&authkey=!ADZkdErqDeWb2cg&ithint=file%2czip).

**Comment by survivor0804** [comment]
You were right. Ansicon 1.70 compiles without problems with the 64-bit tools. No need to edit the Makefile. You must also compile again with the 32-bit tools in order to create ansi32.dll in the x64 folder. It’s used by 32-bit tools like Git.

After issuing ansicon –p, pry’s ansi escape sequences work satisfactorily and Git doesn’t crash anymore. All this works within cmd.exe. It would be ideal for ansicon to work with Git Bash because of nuisances of utf-8 output in cmd.exe.

Thanks!

**Comment by adoxa** [comment]
Did you not update your Git Bash shortcut with the updated ansicon? Or is `ansicon sh` still crashing?

As for UTF-8 in cmd.exe, there's `chcp 65001`, but that doesn't always work with other software (especially `more`). My version of [less](http://less.adoxa.vze.com/) displays UTF-8 files irrespective of the code page.

**Comment by survivor0804** [comment]
ansicon sh no longer crashes but is non-effective. pry’s ansi escapes still not understood by the shell

**Comment by adoxa** [comment]
Well this is annoying - after updating Git & Ruby, it works for me.

```
C:\Program Files (x86)\Git\bin>ansicon --version
ANSICON (64-bit) version 1.70 (26 February, 2014).

C:\Program Files (x86)\Git\bin>ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]

C:\Program Files (x86)\Git\bin>pry --version
Pry version 0.10.1 on Ruby 2.1.6

C:\Program Files (x86)\Git\bin>sh --version
GNU bash, version 3.1.23(6)-release (i686-pc-msys)
Copyright (C) 2005 Free Software Foundation, Inc.

C:\Program Files (x86)\Git\bin>sh --login -i
Welcome to Git (version 1.9.5-preview20150319)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

admin@ADOXA /bin
←[0F[1] pry(main)>

admin@ADOXA /bin
$ logout

C:\Program Files (x86)\Git\bin>ansicon sh --login -i
Welcome to Git (version 1.9.5-preview20150319)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

admin@ADOXA /bin
$ pry
[1] pry(main)>

admin@ADOXA /bin
$ logout
```

**Comment by survivor0804** [comment]
It is working for me too. I started all over, built 1.70 again and tested. It also works with ansicon –p (it didn’t work before so I must have done something wrong). Modifying the Git Bash shortcut is all that is needed. Also, pryrc must be updated since all utf-8 tweaking needed for cmd.exe is no longer necessary.

Thanks
