### ISSUE TITLE
Ansicon doesn't take affect when launching 64 bit java from 32 bit command window

### ISSUE THREAD

**Issue by hyee** [adoxa/ansicon#87]
Hello,

I'm facing the problem when start 64 bit java console(not GUI console) from 32bit command window(`%PROCESSOR_ARCHITECTURE%=x86`), the ansi escape from ansicon doesn't work. 

The version of ansicon is 1.71, even ansi escape doesn't work after java starts, I can still see the `ANSICON` variable defined in current windows' environment, and `%PROCESSOR_ARCHITECTURE%` becomes amd64.

Below is the log:

    ANSICON (64-bit) v1.71 log (5) started 2015-11-09 15:14:07
    ansiconx64 (15952): cmd.exe (15376)
    cmd (15376): hDllInstance = 00670000
    cmd (15376): CreateProcessW: "C:\Soft\Java64\bin\java.exe", "C:\Soft\Java64\bin\java.exe"  -noverify -Xmx384M ...
    cmd (15376): java (17556)
    cmd (15376):   Ignoring apparent 64-bit process (use x64\ansicon)

And if I launch the java console in 64 bit command window, it works fine.

**Comment by adoxa** [comment]
This is the difference between `x86\ANSI32.dll` and `x64\ANSI32.dll` (which has `W32ON64` defined). It also expects `ansicon.exe`, so if you've renamed it to `ansicon64.exe`, you'll have to change `Inject` in `ANSI.c` (around lines 1708-9).

**Comment by hyee** [comment]
Thanks a lot adoxa, according to your comment and the issue is gone.
