### ISSUE TITLE
Arrow key not working when start 'cmd.exe <command>' from a running console

### ISSUE THREAD

**Issue by hyee** [adoxa/ansicon#88]
The steps are:
1.  `ansicon java ...` to start a java console, actually it can be other CLI console, `sqlplus` for example
2.  Inside the java console, launch `cmd /c ...` to suspend current console and switch to another CLI console.
3. Run some commands in the  console, and try to click the arrow up/down keys to visit the command history, and the keys don't work.

Below is the main log:

    ANSICON (32-bit) v1.71 log (21) started 2015-11-09 16:19:49
    ansiconx86 (14320): C:\Soft\Java\bin\java.exe (15312)
    ansiconx86 (14320):   32-bit console (base = 01370000)
    java (15312): hDllInstance = 00AC0000
    java (15312): WriteFile->
    ...
    java (15312): WriteConsoleA: 2 "\r\n"
    java (15312): WriteFile->
    java (15312): WriteConsoleA: 8 "\e[0m\e[0m"
    java (15312): CreateProcessA: "C:\WINDOWS\system32\cmd.exe", C:\WINDOWS\system32\cmd.exe /c "C:\Soft\luajit"
    java (15312): cmd (13908)
    java (15312):   32-bit console (base = 4A6D0000)
    cmd (13908): hDllInstance = 00AC0000
    cmd (13908): CreateProcessW: "C:\Soft\luajit.exe", C:\Soft\luajit
    cmd (13908): luajit (16912)
    cmd (13908):   32-bit console (base = 00400000)
    luajit (16912): hDllInstance = 00AC0000
    luajit (16912): WriteFile->
    luajit (16912): WriteConsoleA: 1 "L"
    luajit (16912): WriteFile->
    luajit (16912): WriteConsoleA: 76 "uaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/\r\n"
    luajit (16912): WriteFile->
    luajit (16912): WriteConsoleA: 7 "JIT: ON"
    luajit (16912): WriteFile->

ansicon -p works fine in this case. 
I also found some other issues in Win 10, i.e. :
1). Intensity: `\e[1;31m` = `\e[31m` != `\e[31;1m` , 
2)  Option `-m<color>` not works well

**Comment by adoxa** [comment]
This is a Windows issue - open the `Properties` dialog, select the `Options` tab and increase the `Number of Buffers`.

**Comment by hyee** [comment]
Thanks again!
