### ISSUE TITLE
Crash when running MSBuild, other processes under latest Windows 10

### ISSUE THREAD

**Issue by hach-que** [adoxa/ansicon#90]
After running `ansicon.exe -i`, most processes like MSBuild and PHP just crash straight out when they are launched.

I've only noticed this problem recently, so it might be a case of a Windows 10 update breaking whatever behaviour or API ANSICON relies on to work.

**Comment by adoxa** [comment]
Is this with 1.66 or [1.70](https://onedrive.live.com/redir?resid=D18DE9C2F9D17ED!127&authkey=!ADZkdErqDeWb2cg&ithint=file%2czip)?

**Comment by hach-que** [comment]
This is 1.66.

**Comment by hach-que** [comment]
Just upgraded to 1.70, will let you know if the issue disappears.

**Comment by hach-que** [comment]
I didn't notice any further issues after upgrading to 1.7.0.
