### ISSUE TITLE
Do not save position ESC [ s  or restore  ESC [ u 

### ISSUE THREAD

**Issue by HommeCurieux** [adoxa/ansicon#93]
Windows 10 x64
ANSICON v1.71

Do not save position ESC [ s  or restore  ESC [ u. 
test batch file:[test2.zip](https://github.com/adoxa/ansicon/files/103676/test2.zip)

```
@ECHO OFF
SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
CLS

IF "%ConEmuANSI%" NEQ "ON" ( "C:\_lib\ANSICON\src\x64\ansicon.exe" -p )

IF NOT DEFINED _ESC_ ( SET "_ESC_=" )

ECHO/ Do not save position^^!>CON

ECHO/%_ESC_%[s>CON
:Loop1
rem ECHO/%_ESC_%[u>CON
SET /A "Num=Num + 1"
ECHO/%_ESC_%[u%_ESC_%[2K%_ESC_%[1;31;40m123%_ESC_%[0m%Num%>CON
pause
GOTO Loop1
```

**Comment by adoxa** [comment]
Redirecting to `CON` causes the console to be opened read-only, preventing retrieval of the current info. I'll fix it for 1.72.
