### ISSUE TITLE
Can't compile Windows 10, gcc 4.8.1

### ISSUE THREAD

**Issue by TickerOfTime** [adoxa/ansicon#96]
No changes to directory structure or code, including makefile.

`make -f makefile.gcc`

```
cmd /c "mkdir x86"
ansicon.c
ansicon.c: In function 'RemoteLoad':
ansicon.c:238:26: error: 'TH32CS_SNAPMODULE32' undeclared (first use in this function)
      TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32, ppi->dwProcessId ))
                          ^
ansicon.c:238:26: note: each undeclared identifier is reported only once for each function it appears in
make: *** [x86/ansicon.o] Error 1
```
If I'm doing something horribly wrong, please let me know. Otherwise would you take a look at this?

**Comment by adoxa** [comment]
Sorry, I hadn't tested MinGW for a while. Quick workaround - replace `TH32CS_SNAPMODULE32` with `0x10`.

**Comment by TickerOfTime** [comment]
Thanks. I ended up writing a little header with classes for the codes anyways. Thanks for your time!
