### ISSUE TITLE
ANSICON: cmd.exe: unsupported process.

### ISSUE THREAD

**Issue by mike-ward** [adoxa/ansicon#97]
On Windows 10, I get this message when open a command prompt. ANSCION works but always displays the message.

![image](https://cloud.githubusercontent.com/assets/567927/14019331/b228a558-f1a8-11e5-8759-070f2488a7c9.png)

**Comment by adoxa** [comment]
Actually, ANSICON doesn't work, because 10 now supports some sequences directly (see #94).

You're probably using the 32-bit (x86) version of ANSICON on 64-bit (x64/AMD64) Windows. `ansicon --version` will tell you what ANSICON is; `set proc` will tell you what `cmd.exe` is.

**Comment by mike-ward** [comment]
That was it. Thanks...
